name: Pull Request Check

on:
  pull_request:
    branches:
      - develop
    types: [opened, reopened, synchronize]

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Npm Install
        run: npm install

      - name: Run Lint
        run: npm run lint

      - name: Run Prettier
        run: npm run prettier

      - name: Run Unit Tests
        run: npm run test
