name: Pull Request Check

on:
  pull_request:
    branches:
      - develop
    types: [opened, reopened, synchronize]

jobs:
  test:
    name: Pull Request Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Npm Install
        run: npm install

      - name: Run Lint Check
        run: npm run lint:check

      - name: Run Format Check
        run: npm run format:check

      - name: Run Type Check
        run: npm run type:check

      - name: Run Unit Tests Check
        run: npm run test
