name: Unit Tests

on:
  push:
    branches:
      - develop

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Npm Install
        run: npm install

      - name: Run Unit Tests
        run: npm run test
